version: 2.1.0.{build}
environment:
  gh_token:
    secure: 3WtkOGm4k++uL56CWe9sJF6HzFAUs7BkM7mvbqdKhkwXOFDtZFIC0k7hM5eGmfLj
  psg_token:
    secure: U6o+x81rGvkEWINVANEKAWw7AYWD/8zNHJ1Akc6adjxK0jIKB2CLx2sTdLUBjL9q
branches:
  only:
  - development
  - master
skip_branch_with_pr: true
skip_tags: true
init:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
install:
  - ps: Install-Module -Name Psake, Pester, PSScriptAnalyzer, PlatyPS, BuildHelpers, GitHubReleaseManager -Force
build_script:
  - ps: .\build.ps1
